# ====================================
import time
# ====================================

# =======================================

print(" Starting.......")
time.sleep(1)
print("      Aegis Development presents...     ")
print(" ")
time.sleep(1)
print("         《★~ Crismon Seas ~★ 》 ")
time.sleep(1)
print("  ")
time.sleep(1)
print("           ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Mochi》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          | Final Messages from your students! |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
print(" ")
time.sleep(3)
print(" ")
print(" ")
print(" ")
print(" ")
print("            ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Mochi》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|") 
time.sleep(1)
print("          |  Please choose a nation:               | ")
time.sleep(1)
print("          | • Iron Blood                           |")
time.sleep(1)
print("          | • Eagle Federation                     |")
time.sleep(1)
print("          | • Hawk Republic                        |")
time.sleep(1)
print("          | • Kitty State                          |")
time.sleep(1)
print("          | • Dragon Empire                        |")
time.sleep(1)
print("          | • Lion Coalition                       |")       
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
