# ====================================
import time
# ====================================

# =======================================

print(" Starting.......")
time.sleep(1)
print(" The class of 2025 presents!!...     ")
print(" ")
time.sleep(1)
print("         《Leaver's message!》 ")
time.sleep(1)
print("  ")
time.sleep(1)
print("           ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Mochi》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          | Final Messages from your students! |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
print(" ")
time.sleep(3)
print(" ")
print(" ")
print(" ")
print(" ")
print("            ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Mochi》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|") 
time.sleep(1)
print("          |  Contributors:                          | ")
time.sleep(1)
print("          | • Leo Liu                               |")
time.sleep(1)
print("          | • John Paskin                           |")
time.sleep(1)
print("          | • Izaac Noble                           |")
time.sleep(1)
print("          | • Aaron Bhatti                          |")
time.sleep(1)
print("          | • Katie Jane Williams                   |")
time.sleep(1)
print("          | • Harry Doyle                           |")
time.sleep(1)
print("          | • Manpreet Rajwansi                     |")  
time.sleep(1)
print("          | • Austin Davies                         |")
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
print("           ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Leo》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          | Thank you so much for all the memories you have given me the last two years!! |")
time.sleep(1)
print("          | I hope the aboslute best for you and your family! You will be missed!         |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
print("           ∧,,,∧")
time.sleep(1)
print("           (=^ᆺ^=) 《John》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          | To Mrs Mayle,                                                                  |")
time.sleep(1)
print("          |                                                                                |")
time.sleep(1)
print("          | Thank you for seeing is though our years,                                      |")
time.sleep(1)
print("          | You are the greatest teacher any student could ask for                        |")
time.sleep(1)
print("          | Thank you for all the fun and memories                                        |")
time.sleep(1)
print("          | I wish you the very best with your future endevous                            |")
time.sleep(1)
print("          | Your next class's will be lucky to have you!                                  |")
time.sleep(1)
print("          | We will All Miss you !!!!                                                     |")
time.sleep(1)
print("          |                                                                               |")
time.sleep(1)
print("          | Good Bye !  o/                                                                |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
print("          |￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          | P.S.        				                             		  |")
time.sleep(1)
print("          | I will try to read the question _AND_ Explain!       |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
print(" :3 ")
time.sleep(1)
print()

print("           ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Izaac》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          |To Mrs Mayle,                                                                  |")
time.sleep(1)
print("          |Thank you for all you have done to help me, your lessons are one of the        |")
time.sleep(1)
print("          |main reasons that I picked computer science as a subject, you always make      |")
time.sleep(1)
print("          |lessons as fun as possible and i really respect you for that, your lessons are |")
time.sleep(1)
print("          |some of the best I have had in my 12 years of being in the education system.   |")
time.sleep(1)
print("          |Thank you for all of this and have a good time at your new school.             |")
time.sleep(1)
print("          | -Izaac Noble         |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
print("           ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Aaron》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          |To Mrs Mayle,                                                                   |")
time.sleep(1)
print("          |Thank you for everything Mrs Mayle! I do wish you all the best from yours truly,|")
time.sleep(1)
print("          | Anime Weeb. Also I wish you all the best for the future!!                      |")
time.sleep(1)
print("          | -Aaron                                                                         |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
print("           ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Katie》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          |To Mrs Mayle,                                                                                                                                                              |")
time.sleep(1)
print("          | thank you so much for everything this past 2 years I don't know how I am passing computer science to be Truley honest you ae a wonderful teacher and amazing person .     |")
time.sleep(1)
print("          | So thank you for that and also for all the support in lessons. I can really see how much effort you have put into this computer science class and as much as it is a darn |")
time.sleep(1)
print("          | shame you are leaving I know you will have an amazing time at your new job and I hope you enjoy it but hopefully you still like this class better than your new ones.     |")
time.sleep(1)
print("          | - Katie                                                                                                                                                                   |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
print("           ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Harry》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          |To Mrs Mayle,                                                                                                                      |")
time.sleep(1)
print("          | Thank you for everything. You were my first tutor and helped me get through the first year back after covid.                      |")
time.sleep(1)
print("          | Thanks for helping me understand computer science and I hope your next school will be just as good as this one.                   |")
time.sleep(1)
print("          | Thank you for all the memories!!                                                                                                  |")
time.sleep(1)
print("          | - Harry                                                                                                                           |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
print("           ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Manpreet》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          |To Mrs Mayle,                                                                         |")
time.sleep(1)
print("          |GOOD LUCK WITH YOUR NEW SCHOOL AND I HOPE YOU GET TO SPEND MORE TIME WITH YOUR FAMILY.|")
time.sleep(1)
print("          | I WISH YOU GOOD LUCK AND PROSPERITY TO YOUR FUTURE!!                                 |")
time.sleep(1)
print("          | -Manpreet                                                                            |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
print("           ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Austin》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          |To Mrs Mayle,                            |")
time.sleep(1)
print("          | We'll miss you                          |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
print("           ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Mochi》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          |           Class of 2025!!!           |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
