# ====================================
import time
# ====================================

# =======================================

print(" Starting.......")
time.sleep(1)
print("      Aegis Development presents...     ")
print(" ")
time.sleep(1)
print("         《★~ Crismon Seas ~★ 》 ")
time.sleep(1)
print("  ")
time.sleep(1)
print("           ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Mochi》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          | Final Messages from your students! |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
print(" ")
time.sleep(3)
print(" ")
print(" ")
print(" ")
print(" ")
print("            ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Mochi》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|") 
time.sleep(1)
print("          |  Contributors:                          | ")
time.sleep(1)
print("          | • Leo Liu                               |")
time.sleep(1)
print("          | • John Paskin                           |")
time.sleep(1)
print("          | • Izaac Noble                           |")
time.sleep(1)
print("          | • Aaron Bhatti                          |")
time.sleep(1)
print("          | • Katie Jane Williams                   |")
time.sleep(1)
print("          | • Harry Doyle                           |")
time.sleep(1)
print("          | • Manpreet Rajwansi                     |")  
time.sleep(1)
print("          | • Austin Davies                         |")
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
print("           ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Leo》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          | Thank you so much for all the memories you have given me the last two years!! |")
time.sleep(1)
print("          | I hope the aboslute best for you and your family! You will be missed!         |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
print("           ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《John》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          | A         |")
time.sleep(1)
print("          | A         |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
print("           ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Izaac》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          |To Mrs Mayle,                                                                  |")
time.sleep(1)
print("          |Thank you for all you have done to help me, your lessons are one of the        |")
time.sleep(1)
print("          |main reasons that I picked computer science as a subject, you always make      |")
time.sleep(1)
print("          |lessons as fun as possible and i really respect you for that, your lessons are |")
time.sleep(1)
print("          |some of the best I have had in my 12 years of being in the education system.   |")
time.sleep(1)
print("          |Thank you for all of this and have a good time at your new school.             |")
time.sleep(1)
print("          | -Izaac Noble         |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
print("           ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Aaron》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          |To Mrs Mayle,                                                                   |")
time.sleep(1)
print("          |Thank you for everything Mrs Mayle! I do wish you all the best from yours truly,|")
time.sleep(1)
print("          | Anime Weeb. Also I wish you all the best for the future!!                      |")
time.sleep(1)
print("          | -Aaron                                                                         |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
print("           ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Katie》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          |To Mrs Mayle,                                                                   |")
time.sleep(1)
print("          |                       |")
time.sleep(1)
print("          |                       |")
time.sleep(1)
print("          | - Katie                                                                        |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
time.sleep(1)
print("           ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Harry》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          |To Mrs Mayle,                                                                   |")
time.sleep(1)
print("          |                       |")
time.sleep(1)
print("          |                       |")
time.sleep(1)
print("          | - Harry                                                                        |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
print("           ∧,,,∧")
time.sleep(1)
print("           (=˃ᆺ˂=) 《Mochi》")
time.sleep(1)
print("          |￣U U￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣|")
time.sleep(1)
print("          |           Class of 2025!!!           |")
time.sleep(1)
print("          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣")
